USE [rrhhloes_]
GO

ALTER TABLE [dbo].[M_USUARIOS_P] DROP CONSTRAINT [DF__M_USUARIO__F_H_C__2B0A656D]
GO

ALTER TABLE [dbo].[M_USUARIOS_P] DROP CONSTRAINT [DF__M_USUARIO__IDEST__2A164134]
GO

/****** Object:  Table [dbo].[M_USUARIOS_P]    Script Date: 16-06-2026 21:19:27 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[M_USUARIOS_P]') AND type in (N'U'))
DROP TABLE [dbo].[M_USUARIOS_P]
GO

/****** Object:  Table [dbo].[M_USUARIOS_P]    Script Date: 16-06-2026 21:19:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[M_USUARIOS_P](
	[IDUSUARIO] [int] IDENTITY(1,1) NOT NULL,
	[RUT] [int] NOT NULL,
	[DV] [char](1) NOT NULL,
	[IDBODEGA] [int] NULL,
	[CODUNIOP] [int] NULL,
	[PASSWD] [varchar](800) NULL,
	[NEW_PASSWD] [int] NULL,
	[NOMBRE] [varchar](400) NOT NULL,
	[NOMBRE_SOCIAL] [varchar](200) NULL,
	[AP_PATERNO] [varchar](200) NOT NULL,
	[AP_MATERNO] [varchar](200) NULL,
	[FECHA_NACIMIENTO] [datetime] NULL,
	[SEXO] [varchar](1) NULL,
	[EST_CIVIL] [int] NULL,
	[DIRECCION] [varchar](400) NULL,
	[IDREGION] [int] NULL,
	[IDCOMUNA] [int] NULL,
	[IDPREVISION] [int] NULL,
	[FONO1] [int] NULL,
	[OBS_FONO1] [varchar](100) NULL,
	[FONO2] [int] NULL,
	[OBS_FONO2] [varchar](100) NULL,
	[EMAIL] [varchar](200) NULL,
	[OBSERVACION] [varchar](500) NULL,
	[IDESTADO] [int] NOT NULL,
	[IDUSERCREA] [int] NOT NULL,
	[F_H_CREA] [datetime] NOT NULL,
	[IDUSERMOD] [int] NULL,
	[F_H_MOD] [datetime] NULL,
 CONSTRAINT [PK_M_IDUSUARIO] PRIMARY KEY CLUSTERED 
(
	[IDUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_M_USUARIOS_RUT] UNIQUE NONCLUSTERED 
(
	[RUT] ASC,
	[DV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[M_USUARIOS_P] ADD  DEFAULT ((1)) FOR [IDESTADO]
GO

ALTER TABLE [dbo].[M_USUARIOS_P] ADD  DEFAULT (getdate()) FOR [F_H_CREA]
GO

ALTER TABLE [dbo].[M_USUARIOS_P] ADD  DEFAULT (getdate()) FOR [F_H_MOD]
GO


